### ISSUE TITLE
Spelling error "Cocka" Cola

### ISSUE THREAD

**Issue by rnayabed** [tevyecowan/VendingMachine#2]
I think there is a spelling mistake in the app. The vending app has a button called "Cocka Cola" which i think is an incorrect spelling of the "Coca Cola". Was this purposely done as a joke? :laughing: :confused:

**Comment by rnayabed** [comment]
Lol why did you just simply close the issue?

**Comment by tevyecowan** [comment]
The spelling was intentional, all the drinks are parody versions of the
actual drinks. I haven't worked on it in ages, but I do intent to
eventually finish the program!

**Comment by rnayabed** [comment]
Yes go ahead. I have been commenting on several dead projects, glad that someone replied!
